ResumeBuilder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ResumePage.urls")),
]

ResumePage/urls.py
from django.urls import path
from . import views

app_name = 'ResumePage'

urlpatterns = [
    path('', views.home, name='home'),
    path('resume_list/', views.resume_list, name='resume_list'),
    path('resume_detail/<int:pk>/', views.resume_detail, name='resume_detail'),

    path('resume_delete/<int:pk>/', views.resume_delete, name='resume_delete'),
    path('resume_new/', views.resume_new, name='resume_new'),
]

ResumePage/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Resume(models.Model):
    full_name = models.CharField(max_length=100)
    profile_summary = models.TextField()
    education = models.TextField(blank=True)
    skills = models.TextField()
    work_experience = models.TextField(blank=True)
    email = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=15)

    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('ResumePage:resume_detail', kwargs={'pk': self.pk})

ResumePage/forms.py
from django import forms

from ResumePage.models import Resume
import re


def is_valid_email(email):
    pattern = r"[^@]+@[^@]+\.[^@]+"
    return bool(re.match(pattern, email))


class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['full_name', 'profile_summary', 'education', 'skills',
                  'work_experience', 'email', 'phone_number']

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.get('instance', None)
        super().__init__(*args, **kwargs)

    def clean_full_name(self, *args, **kwargs):
        full_name = self.cleaned_data.get('full_name')
        for character in full_name:
            if not character.isalpha():
                raise forms.ValidationError("Please enter a valid full name")
        return full_name

    def clean_email(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        if not is_valid_email(email):
            raise forms.ValidationError("Please enter a valid email address")
        return email

    def clean_phone_number(self, *args, **kwargs):
        phone_number = self.cleaned_data.get('phone_number')
        if len(phone_number) < 11 or not phone_number.isdigit():
            raise forms.ValidationError("Please enter a valid phone number")
        return phone_number


class ResumeDetailForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['full_name', 'profile_summary', 'education', 'skills',
                  'work_experience', 'email', 'phone_number']

    def __init__(self, *args, **kwargs):
        super(ResumeDetailForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['readonly'] = True

ResumePage/views.py
from django.shortcuts import render, get_object_or_404, redirect

from ResumePage.forms import ResumeForm, ResumeDetailForm
from ResumePage.models import Resume


# Create your views here.
def home(request):
    return render(request, "ResumePage/index.html", {})


def resume_list(request):
    resumes = Resume.objects.all()
    return render(request, "ResumePage/list.html", {'resume_list': resumes})


def resume_detail(request, pk):
    resume = get_object_or_404(Resume, pk=pk)
    resume_form = ResumeDetailForm(request.POST or None, instance=resume)
    return render(request, "ResumePage/detail.html", {"form": resume_form})


def resume_delete(request, pk):
    resume = get_object_or_404(Resume, pk=pk)
    resume.delete()
    return redirect("ResumePage:resume_list")


def resume_new(request):
    if request.method == "POST":
        form = ResumeForm(request.POST or None)
        if form.is_valid():
            full_name = form.cleaned_data["full_name"]
            profile_summary = form.cleaned_data["profile_summary"]
            education = form.cleaned_data["education"]
            skills = form.cleaned_data["skills"]
            work_experience = form.cleaned_data["work_experience"]
            email = form.cleaned_data["email"]
            phone_number = form.cleaned_data["phone_number"]
            resume = Resume(full_name=full_name, profile_summary=profile_summary,
                            education=education, skills=skills, work_experience=work_experience,
                            email=email, phone_number=phone_number)
            resume.save()
            return redirect("ResumePage:home")
        else:
            form.add_error(None, 'Invalid information')
            print(form.errors)
            return redirect("ResumePage:home")
    else:
        form = ResumeForm()
        return render(request, "ResumePage/create.html", {"form": form})

templates/404_page.html
{% extends 'base.html' %}

{% block title_block %}
	
{% endblock %}


{% block body_block %}
	
{% endblock %}

templates/ResumePage/create.html
{% extends 'base.html' %}

{% block title_block %}
	Create Resume
{% endblock %}


{% block body_block %}
	<form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">create</button>
        <a href="{% url 'ResumePage:home' %}">main page</a>
    </form>
{% endblock %}

templates/ResumePage/detail.html
{% extends 'base.html' %}

{% block title_block %}
	Resume Detail
{% endblock %}


{% block body_block %}
    <a href="{% url 'ResumePage:home' %}">main page</a>
	{{ form.as_p }}
{% endblock %}

templates/ResumePage/index.html
{% extends 'base.html' %}

{% block title_block %}
	Home Page
{% endblock %}


{% block body_block %}
	<h2>
        free online platform to build resume, and see what others have built.
        note: every 24 hours the database gets cleaned.
    </h2>
    
    <a href="{% url 'ResumePage:resume_new' %}">
        <p>create new resume</p>
    </a>
    
    <a href="{% url 'ResumePage:resume_list' %}">
        <p>see the list of all resumes</p>
    </a>
    
{% endblock %}

templates/ResumePage/list.html
{% extends 'base.html' %}

{% block title_block %}
	<title>Resume List</title>
{% endblock %}


{% block body_block %}
    <a href="{% url 'ResumePage:home' %}">main page</a>
	<ul>
        {% for resume in resume_list %}
        	<li style="display-inside: ruby;">
                <p>
                    <a href='{{ resume.get_absolute_url }}'/>
                    {{ resume.pk }}  - {{ resume.full_name }}
                </p>
                
                <form method="get" action="{% url 'ResumePage:resume_delete' resume.pk %}"> 
                    <button type="submit">delete</button>
                </form>
            </li>
        {% endfor %}
        
    </ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title_block %}
        {% endblock %}
    </title>
</head>
<body>
    {% block body_block %}
    	
    {% endblock %}
</body>
</html>